# In-class classification exercise

## Just like what we did in the regression exercise, do the following: 

0. Fork the course project 
1. Find a dataset (Kaggle, Sci-kit learn, Hugging Face, ...)
2. EDA on the data 
3. Select the feature
4. Build a model using Logistic regression 
5. Evaluate the model you just built with the according metrices 
6. Git add, commit and push to your fork https://www.atlassian.com/git/tutorials/setting-up-a-repository 
7. Create a Pull Request on your work

In [7]:
import pandas as pd
import numpy as np 
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris

In [17]:
iris = load_iris(as_frame=True)

In [18]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [45]:
X = iris.data

In [46]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB

In [47]:
X.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [48]:
X.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [49]:
X = X[['sepal length (cm)', "sepal width (cm)"]]

In [50]:
X

     sepal length (cm)  sepal width (cm)
0                  5.1               3.5
1                  4.9               3.0
2                  4.7               3.2
3                  4.6               3.1
4                  5.0               3.6
..                 ...               ...
145                6.7               3.0
146                6.3               2.5
147                6.5               3.0
148                6.2               3.4
149                5.9               3.0

[150 rows x 2 columns]

In [24]:
y = iris.target

In [26]:
y.value_counts()

target
0    50
1    50
2    50
Name: count, dtype: int64

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [27]:
classifier = LogisticRegression(C=0.5)

In [30]:
classifier.fit(X_train, y_train)

LogisticRegression(C=0.5)

In [31]:
classifier.score(X_test, y_test)

0.9

In [32]:
predictions = classifier.predict(X_test)

In [33]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

accuracy = accuracy_score(y_test, predictions)
precision = precision_score(y_test, predictions, average='weighted')
recall = recall_score(y_test, predictions, average='weighted')
f1 = f1_score(y_test, predictions, average='weighted')

accuracy, precision, recall, f1

(0.9,
 np.float64(0.9032828282828282),
 np.float64(0.9),
 np.float64(0.9003809523809524))

In [35]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       0.82      0.90      0.86        10
           2       0.92      0.85      0.88        13

    accuracy                           0.90        30
   macro avg       0.91      0.92      0.91        30
weighted avg       0.90      0.90      0.90        30