# In-class classification exercise

## Just like what we did in the regression exercise, do the following: 

0. Fork the course project 
1. Find a dataset (Kaggle, Sci-kit learn, Hugging Face, ...)
2. EDA on the data 
3. Select the feature
4. Build a model using Logistic regression 
5. Evaluate the model you just built with the according metrices 
6. Git add, commit and push to your fork https://www.atlassian.com/git/tutorials/setting-up-a-repository 
7. Create a Pull Request on your work

In [3]:
import pandas as pd
import numpy as np 
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [2]:
!kaggle datasets download -d heptapod/titanic -p ../../data/temp_large/kaggle_tantanic --unzip

Dataset URL: https://www.kaggle.com/datasets/heptapod/titanic
License(s): DbCL-1.0
Downloading titanic.zip to ../../data/temp_large/kaggle_tantanic
  0%|                                               | 0.00/10.8k [00:00<?, ?B/s]
100%|██████████████████████████████████████| 10.8k/10.8k [00:00<00:00, 24.2MB/s]

In [4]:
df = pd.read_csv('../../data/temp_large/kaggle_tantanic/train_and_test2.csv')
df.head()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

In [5]:
df.columns

Index(['Passengerid', 'Age', 'Fare', 'Sex', 'sibsp', 'zero', 'zero.1',
       'zero.2', 'zero.3', 'zero.4', 'zero.5', 'zero.6', 'Parch', 'zero.7',
       'zero.8', 'zero.9', 'zero.10', 'zero.11', 'zero.12', 'zero.13',
       'zero.14', 'Pclass', 'zero.15', 'zero.16', 'Embarked', 'zero.17',
       'zero.18', '2urvived'],
      dtype='object')

In [6]:
df.drop(columns=['sibsp', 'zero', 'zero.1',
       'zero.2', 'zero.3', 'zero.4', 'zero.5', 'zero.6', 'Parch', 'zero.7',
       'zero.8', 'zero.9', 'zero.10', 'zero.11', 'zero.12', 'zero.13',
       'zero.14', 'Pclass', 'zero.15', 'zero.16', 'Embarked', 'zero.17',
       'zero.18',], inplace=True)

In [7]:
df.head()

   Passengerid   Age     Fare  Sex  2urvived
0            1  22.0   7.2500    0         0
1            2  38.0  71.2833    1         1
2            3  26.0   7.9250    1         1
3            4  35.0  53.1000    1         1
4            5  35.0   8.0500    0         0

In [8]:
X = df[['Sex', 'Age', 'Fare']]

In [9]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Sex     1309 non-null   int64
 1   Age     1309 non-null   float64
 2   Fare    1309 non-null   float64
dtypes: float64(2), int64(1)
memory usage: 30.8 KB

In [10]:
X.describe()

               Sex          Age         Fare
count  1309.000000  1309.000000  1309.000000
mean      0.355997    29.503186    33.281086
std       0.478997    12.905241    51.741500
min       0.000000     0.170000     0.000000
25%       0.000000    22.000000     7.895800
50%       0.000000    28.000000    14.454200
75%       1.000000    35.000000    31.275000
max       1.000000    80.000000   512.329200

In [11]:
X.Sex.value_counts()

Sex
0    843
1    466
Name: count, dtype: int64

In [12]:
X.columns

Index(['Sex', 'Age', 'Fare'], dtype='object')

In [13]:
y = df['2urvived']

In [14]:
y.value_counts()

2urvived
0    967
1    342
Name: count, dtype: int64

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [16]:
classifier = LogisticRegression(C=0.9)

In [17]:
classifier.fit(X_train, y_train)

LogisticRegression(C=0.9)

In [18]:
classifier.score(X_test, y_test)

0.7786259541984732

In [19]:
predictions = classifier.predict(X_test)

predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [20]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

accuracy = accuracy_score(y_test, predictions)
precision = precision_score(y_test, predictions, average='weighted')
recall = recall_score(y_test, predictions, average='weighted')
f1 = f1_score(y_test, predictions, average='weighted')

accuracy, precision, recall, f1

(0.7786259541984732, 0.750678087423556, 0.7786259541984732, 0.7565433180611215)

In [21]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.82      0.92      0.87       203
           1       0.51      0.31      0.38        59

    accuracy                           0.78       262
   macro avg       0.67      0.61      0.62       262
weighted avg       0.75      0.78      0.76       262

In [22]:
classifier.coef_, classifier.intercept_

(array([[ 1.68103603, -0.0112211 ,  0.0067193 ]]), array([-1.67537603]))

In [24]:
from sklearn.metrics import log_loss

log_loss(y_test, predictions)

7.979129376216774

In [33]:
def _log_loss(y_true, y_pred):
    epsilon = 1e-15
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)
    n = y_true.shape[0]
    loss = - (1/n) * np.sum(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))
    return loss

In [25]:
def custom_log_loss(y_true, y_pred):
    return _log_loss(y_true, y_pred)

In [34]:
custom_log_loss(y_test, predictions)

np.float64(7.646040549851652)

In [32]:
np.log(0)

/var/folders/0x/3ms0bnbn6196rf0m4bwzwdrm0000gn/T/ipykernel_26423/2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)

np.float64(-inf)

In [50]:
predictions.dtype

dtype('int64')

In [51]:
y_prob = classifier.predict_proba(X_test)

In [52]:
np.finfo(y_prob.dtype).eps

np.float64(2.220446049250313e-16)

In [56]:
y_prob.dtype

dtype('float64')

In [ ]:
np.finfo(predictions.dtype).eps

ValueError: data type <class 'numpy.int64'> not inexact