### Note: 
Kaggle API/CLI way of downloading the dataset wse used below. 
https://www.kaggle.com/discussions/general/156610

In [1]:
!pip install --user kaggle

Collecting kaggle
  Downloading kaggle-1.7.4.5-py3-none-any.whl.metadata (16 kB)
Collecting bleach (from kaggle)
  Downloading bleach-6.2.0-py3-none-any.whl.metadata (30 kB)
Collecting certifi>=14.05.14 (from kaggle)
  Downloading certifi-2025.8.3-py3-none-any.whl.metadata (2.4 kB)
Collecting charset-normalizer (from kaggle)
  Downloading charset_normalizer-3.4.2-cp311-cp311-macosx_10_9_universal2.whl.metadata (35 kB)
Collecting idna (from kaggle)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting protobuf (from kaggle)
  Downloading protobuf-6.31.1-cp39-abi3-macosx_10_9_universal2.whl.metadata (593 bytes)
Requirement already satisfied: python-dateutil>=2.5.3 in /Users/yusali/miniforge3/envs/ML_intro/lib/python3.11/site-packages (from kaggle) (2.9.0.post0)
Collecting python-slugify (from kaggle)
  Downloading python_slugify-8.0.4-py2.py3-none-any.whl.metadata (8.5 kB)
Collecting requests (from kaggle)
  Downloading requests-2.32.4-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: setuptools>=21.0.0 in /Users/yusali/miniforge3/envs/ML_intro/lib/python3.11/site-packages (from kaggle) (80.9.0)
Requirement already satisfied: six>=1.10 in /Users/yusali/miniforge3/envs/ML_intro/lib/python3.11/site-packages (from kaggle) (1.17.0)
Collecting text-unidecode (from kaggle)
  Downloading text_unidecode-1.3-py2.py3-none-any.whl.metadata (2.4 kB)
Collecting tqdm (from kaggle)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting urllib3>=1.15.1 (from kaggle)
  Downloading urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
Collecting webencodings (from kaggle)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Downloading kaggle-1.7.4.5-py3-none-any.whl (181 kB)
Downloading certifi-2025.8.3-py3-none-any.whl (161 kB)
Downloading urllib3-2.5.0-py3-none-any.whl (129 kB)
Downloading bleach-6.2.0-py3-none-any.whl (163 kB)
Downloading charset_normalizer-3.4.2-cp311-cp311-macosx_10_9_universal2.whl (198 kB)
Downloading idna-3.10-py3-none-any.whl (70 kB)
Downloading protobuf-6.31.1-cp39-abi3-macosx_10_9_universal2.whl (425 kB)
Downloading python_slugify-8.0.4-py2.py3-none-any.whl (10 kB)
Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Downloading requests-2.32.4-py3-none-any.whl (64 kB)
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, text-unidecode, urllib3, tqdm, python-slugify, protobuf, idna, charset-normalizer, certifi, bleach, requests, kaggle
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/12 [kaggle]11/12 [kaggle]
Successfully installed bleach-6.2.0 certifi-2025.8.3 charset-normalizer-3.4.2 idna-3.10 kaggle-1.7.4.5 protobuf-6.31.1 python-slugify-8.0.4 requests-2.32.4 text-unidecode-1.3 tqdm-4.67.1 urllib3-2.5.0 webencodings-0.5.1

In [3]:
!kaggle datasets list -s nilesh2042/the-worlds-billionaires-by-forbes

ref                                           title                                          size  lastUpdated                 downloadCount  voteCount  usabilityRating
--------------------------------------------  ---------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
nilesh2042/the-worlds-billionaires-by-forbes  THE WORLD'S BILLIONAIRES by Forbes 2025       36367  2025-07-28 12:58:26.540000            143         17  1.0

In [4]:
!kaggle datasets download -d nilesh2042/the-worlds-billionaires-by-forbes -p ../../data/temp_large/kaggle_billionaires --unzip

Dataset URL: https://www.kaggle.com/datasets/nilesh2042/the-worlds-billionaires-by-forbes
License(s): CC0-1.0
Downloading the-worlds-billionaires-by-forbes.zip to ../../data/temp_large/kaggle_billionaires
  0%|                                               | 0.00/35.5k [00:00<?, ?B/s]
100%|███████████████████████████████████████| 35.5k/35.5k [00:00<00:00, 146MB/s]

In [1]:
!kaggle datasets download -h

usage: kaggle datasets download [-h] [-f FILE_NAME] [-p PATH] [-w] [--unzip]
                                [-o] [-q]
                                [dataset]

options:
  -h, --help            show this help message and exit
  dataset               Dataset URL suffix in format <owner>/<dataset-name> (use "kaggle datasets list" to show options)
  -f FILE_NAME, --file FILE_NAME
                        File name, all files downloaded if not provided
                        (use "kaggle datasets files -d <dataset>" to show options)
  -p PATH, --path PATH  Folder where file(s) will be downloaded, defaults to current working directory
  -w, --wp              Download files to current working path
  --unzip               Unzip the downloaded file. Will delete the zip file when completed.
  -o, --force           Skip check whether local version of file is up to date, force file download
  -q, --quiet           Suppress printing information about the upload/download progress

In [ ]:
import os
from kaggle.api.kaggle_api_extended import KaggleApi

In [5]:
import pandas as pd

In [4]:
df = pd.read_csv("../../data/temp_large/kaggle_reuters/ModApte_test.csv")

In [5]:
df.head()

,text,text_type,topics,lewis_split,cgis_split,old_id,new_id,places,people,orgs,exchanges,date,title
0,Mounting trade friction between the\nU.S. And ...,"""NORM""",['trade'],"""TEST""","""TRAINING-SET""","""3809""","""14826""",['hong-kong' 'usa' 'japan' 'taiwan' 'malaysia'...,[],[],[],8-APR-1987 01:03:47.52,ASIAN EXPORTERS FEAR DAMAGE FROM U.S.-JAPAN RIFT
1,A survey of 19 provinces and seven cities\nsho...,"""NORM""",['grain'],"""TEST""","""TRAINING-SET""","""3811""","""14828""",['china'],[],[],[],8-APR-1987 01:19:17.29,CHINA DAILY SAYS VERMIN EAT 7-12 PCT GRAIN STOCKS
2,The Ministry of International Trade and\nIndus...,"""NORM""",['crude' 'nat-gas'],"""TEST""","""TRAINING-SET""","""4356""","""14829""",['japan'],[],[],[],8-APR-1987 01:22:17.25,JAPAN TO REVISE LONG-TERM ENERGY DEMAND DOWNWARDS
3,Thailand's trade deficit widened to 4.5\nbilli...,"""NORM""",['trade' 'grain' 'rice' 'corn' 'sugar' 'tin' '...,"""TEST""","""TRAINING-SET""","""3815""","""14832""",['thailand'],[],[],[],8-APR-1987 01:45:09.09,THAI TRADE DEFICIT WIDENS IN FIRST QUARTER
4,Indonesia expects crude palm oil (CPO)\nprices...,"""NORM""",['veg-oil' 'palm-oil'],"""TEST""","""TRAINING-SET""","""3816""","""14833""",['indonesia' 'malaysia'],[],[],[],8-APR-1987 01:48:20.11,INDONESIA SEES CPO PRICE RISING SHARPLY

In [6]:
df.shape

(3299, 13)

In [7]:
df.describe()

,text,text_type,topics,lewis_split,cgis_split,old_id,new_id,places,people,orgs,exchanges,date,title
count,3023,3299,3299,3299,3299,3299,3299,3299,3299,3299,3299,3299,3285
unique,3004,3,258,1,1,3299,3299,359,76,22,13,3299,3220
top,The leaders of two of Japan's top business\ngr...,"""NORM""",['earn'],"""TEST""","""TRAINING-SET""","""3809""","""14826""",['usa'],[],[],[],8-APR-1987 01:03:47.52,PROPOSED OFFERINGS RECENTLY FILED WITH THE SEC
freq,2,3009,1083,3299,3299,1,1,1786,3127,3132,3276,1,4